CREATE TABLE nourriture (
    nourriture_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, 
    nourriture_nom VARCHAR2(150) NOT NULL,
    nourriture_prix NUMBER,               
    nourriture_date_arr DATE,                  
    nourriture_date_exp DATE,            
    nourriture_quantite INTEGER,          
    nourriture_origine VARCHAR2(150)                 
);

CREATE TABLE acheteur (
    acheteur_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    acheteur_nom VARCHAR2(150) NOT NULL UNIQUE,
    acheteur_email VARCHAR2(150),
    acheteur_TypeDeMembre VARCHAR2(50)
);

INSERT INTO nourriture (nourriture_nom, nourriture_prix, nourriture_date_arr, nourriture_date_exp, nourriture_quantite, nourriture_origine) 
VALUES ('Pommes', 2.50, TO_DATE('2026-05-10', 'YYYY-MM-DD'), TO_DATE('2026-06-10', 'YYYY-MM-DD'), 100, 'France');

INSERT INTO nourriture (nourriture_nom, nourriture_prix, nourriture_date_arr, nourriture_date_exp, nourriture_quantite, nourriture_origine) 
VALUES ('Fraises', 1.80, TO_DATE('2026-05-12', 'YYYY-MM-DD'), TO_DATE('2026-05-26', 'YYYY-MM-DD'), 250, 'Espagne');

INSERT INTO nourriture (nourriture_nom, nourriture_prix, nourriture_date_arr, nourriture_date_exp, nourriture_quantite, nourriture_origine) 
VALUES ('Huile d''olive', 4.20, TO_DATE('2026-05-14', 'YYYY-MM-DD'), TO_DATE('2026-07-14', 'YYYY-MM-DD'), 80, 'Italie');

INSERT INTO nourriture (nourriture_nom, nourriture_prix, nourriture_date_arr, nourriture_date_exp, nourriture_quantite, nourriture_origine) 
VALUES ('Tomates Cerises', 0.99, TO_DATE('2026-05-15', 'YYYY-MM-DD'), TO_DATE('2026-05-22', 'YYYY-MM-DD'), 500, 'Maroc');

INSERT INTO nourriture (nourriture_nom, nourriture_prix, nourriture_date_arr, nourriture_date_exp, nourriture_quantite, nourriture_origine) 
VALUES ('Chocolat Belge', 5.50, TO_DATE('2026-05-16', 'YYYY-MM-DD'), TO_DATE('2026-05-30', 'YYYY-MM-DD'), 60, 'Belgique');

INSERT INTO nourriture (nourriture_nom, nourriture_prix, nourriture_date_arr, nourriture_date_exp, nourriture_quantite, nourriture_origine) 
VALUES ('Oranges', 3.10, TO_DATE('2026-05-17', 'YYYY-MM-DD'), TO_DATE('2026-06-17', 'YYYY-MM-DD'), 150, 'Portugal');

INSERT INTO nourriture (nourriture_nom, nourriture_prix, nourriture_date_arr, nourriture_date_exp, nourriture_quantite, nourriture_origine) 
VALUES ('Café en grains', 12.00, TO_DATE('2026-05-18', 'YYYY-MM-DD'), TO_DATE('2026-08-18', 'YYYY-MM-DD'), 30, 'Colombie');

INSERT INTO nourriture (nourriture_nom, nourriture_prix, nourriture_date_arr, nourriture_date_exp, nourriture_quantite, nourriture_origine) 
VALUES ('Fromage Gouda', 2.20, TO_DATE('2026-05-19', 'YYYY-MM-DD'), TO_DATE('2026-06-02', 'YYYY-MM-DD'), 200, 'Pays-Bas');

INSERT INTO nourriture (nourriture_nom, nourriture_prix, nourriture_date_arr, nourriture_date_exp, nourriture_quantite, nourriture_origine) 
VALUES ('Feta', 7.85, TO_DATE('2026-05-19', 'YYYY-MM-DD'), TO_DATE('2026-09-01', 'YYYY-MM-DD'), 45, 'Grèce');

INSERT INTO nourriture (nourriture_nom, nourriture_prix, nourriture_date_arr, nourriture_date_exp, nourriture_quantite, nourriture_origine) 
VALUES ('Pain de seigle', 1.50, TO_DATE('2026-05-19', 'YYYY-MM-DD'), TO_DATE('2026-05-29', 'YYYY-MM-DD'), 300, 'Allemagne');

INSERT INTO nourriture (nourriture_nom, nourriture_prix, nourriture_date_arr, nourriture_date_exp, nourriture_quantite, nourriture_origine) 
VALUES ('Sirop d''érable', 9.99, TO_DATE('2026-05-20', 'YYYY-MM-DD'), TO_DATE('2027-05-20', 'YYYY-MM-DD'), 75, 'Canada');

INSERT INTO nourriture (nourriture_nom, nourriture_prix, nourriture_date_arr, nourriture_date_exp, nourriture_quantite, nourriture_origine) 
VALUES ('Riz Basmati', 3.50, TO_DATE('2026-05-21', 'YYYY-MM-DD'), TO_DATE('2028-05-21', 'YYYY-MM-DD'), 400, 'Inde');

INSERT INTO nourriture (nourriture_nom, nourriture_prix, nourriture_date_arr, nourriture_date_exp, nourriture_quantite, nourriture_origine) 
VALUES ('Avocats', 4.50, TO_DATE('2026-05-22', 'YYYY-MM-DD'), TO_DATE('2026-06-05', 'YYYY-MM-DD'), 120, 'Mexique');

INSERT INTO nourriture (nourriture_nom, nourriture_prix, nourriture_date_arr, nourriture_date_exp, nourriture_quantite, nourriture_origine) 
VALUES ('Saumon Fumé', 14.90, TO_DATE('2026-05-23', 'YYYY-MM-DD'), TO_DATE('2026-06-12', 'YYYY-MM-DD'), 50, 'Norvège');

INSERT INTO nourriture (nourriture_nom, nourriture_prix, nourriture_date_arr, nourriture_date_exp, nourriture_quantite, nourriture_origine) 
VALUES ('Kiwis', 2.99, TO_DATE('2026-05-24', 'YYYY-MM-DD'), TO_DATE('2026-06-24', 'YYYY-MM-DD'), 180, 'Nouvelle-Zélande');



INSERT INTO acheteur (acheteur_nom, acheteur_email, acheteur_TypeDeMembre) 
VALUES ('Jean Dupont', 'jean.dupont@email.com', 'Premium');

INSERT INTO acheteur (acheteur_nom, acheteur_email, acheteur_TypeDeMembre) 
VALUES ('Marie Martin', 'marie.martin@email.com', 'Standard');

INSERT INTO acheteur (acheteur_nom, acheteur_email, acheteur_TypeDeMembre) 
VALUES ('Pierre Bernard', 'pierre.bernard@email.com', 'Standard');

INSERT INTO acheteur (acheteur_nom, acheteur_email, acheteur_TypeDeMembre) 
VALUES ('Chloé Petit', 'chloe.petit@email.com', 'Premium');

INSERT INTO acheteur (acheteur_nom, acheteur_email, acheteur_TypeDeMembre) 
VALUES ('Thomas Roux', 'thomas.roux@email.com', 'Standard');

INSERT INTO acheteur (acheteur_nom, acheteur_email, acheteur_TypeDeMembre) 
VALUES ('Julie David', 'julie.david@email.com', 'Premium');

INSERT INTO acheteur (acheteur_nom, acheteur_email, acheteur_TypeDeMembre) 
VALUES ('Kevin Morel', 'kevin.morel@email.com', 'Standard');

INSERT INTO acheteur (acheteur_nom, acheteur_email, acheteur_TypeDeMembre) 
VALUES ('Sarah Simon', 'sarah.simon@email.com', 'Premium');

INSERT INTO acheteur (acheteur_nom, acheteur_email, acheteur_TypeDeMembre) 
VALUES ('Lucas Laurent', 'lucas.laurent@email.com', 'Standard');

INSERT INTO acheteur (acheteur_nom, acheteur_email, acheteur_TypeDeMembre) 
VALUES ('Emma Garcia', 'emma.garcia@email.com', 'Premium');

COMMIT;
